[package]
name = "rust-huge-table"
version = "0.1.0"
authors = ["Arno Haase <arno.haase@haase-consulting.com>"]
edition = "2018"


[dependencies]
env_logger = "0.7"
fasthash = "0.4"
log = "0.4"
memmap = "0.7"
uuid = {version = "0.8", features = ["v1", "v4"]}
